export const assignments = [
  {
    id: "a1",
    title: "Packaging Design Concept",
    description: "Design a packaging concept for a new product.",
    course: "Visual Communication",
    dueDate: "25 March 2026",
    daysRemaining: 3,
    attachments: 2,
    points: 20,
    priority: "high",
  },
  {
    id: "a2",
    title: "Typography Poster",
    description: "Create a poster using expressive typography.",
    course: "Graphic Design",
    dueDate: "28 March 2026",
    daysRemaining: 6,
    attachments: 1,
    points: 15,
    priority: "medium",
  },
  {
    id: "a3",
    title: "Brand Identity Research",
    description: "Research 3 brands and analyze their identity systems.",
    course: "Brand Strategy",
    dueDate: "30 March 2026",
    daysRemaining: 8,
    attachments: 3,
    points: 25,
    priority: "low",
  },
  {
    id: "a4",
    title: "UI Wireframe Submission",
    description: "Create low-fidelity wireframes for a mobile app.",
    course: "UI/UX Fundamentals",
    dueDate: "2 April 2026",
    daysRemaining: 11,
    attachments: 2,
    points: 30,
    priority: "medium",
  },
];

export const notifications = [
  {
    id: "n1",
    title: "Assignment Due Soon",
    message: "Packaging Design Concept is due in 3 days.",
    course: "Visual Communication",
    time: "10 minutes ago",
    type: "assignment",
    priority: "high",
    isRead: false,
  },
  {
    id: "n2",
    title: "New Lecture Uploaded",
    message: "Week 4 Typography lecture slides have been uploaded.",
    course: "Graphic Design",
    time: "1 hour ago",
    type: "lecture",
    priority: "low",
    isRead: false,
  },
  {
    id: "n3",
    title: "Grades Released",
    message: "Your Brand Identity Research assignment has been graded.",
    course: "Brand Strategy",
    time: "Yesterday",
    type: "grades",
    priority: "medium",
    isRead: true,
  },
  {
    id: "n4",
    title: "System Announcement",
    message: "The LMS will undergo maintenance tonight at 11 PM.",
    course: "System",
    time: "2 hours ago",
    type: "system",
    priority: "medium",
    isRead: false,
  },
];

export const courses = [
  {
    id: "c1",
    title: "Discrete Mathematics",
    description:
      "Explore the mathematics behind algorithms, graphs, logic, and discrete structures.",
    instructor: "Dr. Alan Turing",
    progress: 66,
    lessons: 12,
    assignments: 4,
    image:
      "https://images.unsplash.com/photo-1628595351029-c2bf17511435?q=80&w=1032&auto=format&fit=crop",
  },
  {
    id: "c2",
    title: "Data Structures",
    description: "Learn stacks, queues, trees, graphs and algorithm analysis.",
    instructor: "Prof. Donald Knuth",
    progress: 45,
    lessons: 18,
    assignments: 6,
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
  },
  {
    id: "c3",
    title: "Operating Systems",
    description:
      "Understand memory management, processes, threads and scheduling.",
    instructor: "Dr. Andrew Tanenbaum",
    progress: 82,
    lessons: 14,
    assignments: 5,
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
  },
  {
    id: "c4",
    title: "Machine Learning",
    description:
      "Introduction to supervised and unsupervised learning algorithms.",
    instructor: "Dr. Geoffrey Hinton",
    progress: 25,
    lessons: 20,
    assignments: 8,
    image: "https://images.unsplash.com/photo-1526378722484-bd91ca387e72",
  },
];

import { GoCommentDiscussion } from "react-icons/go";

export const calendarEvents = [
  {
    id: 1,
    title: "Machine Learning Lecture",
    time: "09:00 – 10:30",
    course: "Room A203",
    icon: GoCommentDiscussion,
  },
  {
    id: 2,
    title: "Database Systems Assignment",
    time: "11:59 Deadline",
    course: "Submission",
    icon: GoCommentDiscussion,
  },
  {
    id: 3,
    title: "UI/UX Design Workshop",
    time: "12:40 – 13:30",
    course: "Design Lab",
    icon: GoCommentDiscussion,
  },
  {
    id: 4,
    title: "Operating Systems Lecture",
    time: "14:00 – 15:30",
    course: "Room B104",
    icon: GoCommentDiscussion,
  },
  {
    id: 5,
    title: "Data Structures Study Group",
    time: "17:00 – 18:00",
    course: "Library Room 2",
    icon: GoCommentDiscussion,
  },
];
