import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { ApolloWrapper } from "./ApolloWrapper";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SessionProvider } from "@/context/session-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="m-0 p-0 h-full overflow-y-auto"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex overflow-y-auto flex-col min-h-[100vh]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <Toaster position="top-center" />
          <SessionProvider>
            <ApolloWrapper>
              <SidebarProvider>{children}</SidebarProvider>
            </ApolloWrapper>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
